// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package com.rainerschuster.cardgames.client;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface MyCss extends CssResource {
  
  @ClassName("cg-Card")
  String cgCard();
  
  @ClassName("cg-Pile")
  String cgPile();
  
  @ClassName("cg-sidePlaceholder")
  String cgSidePlaceholder();
  
  @ClassName("cg-Table")
  String cgTable();
}

